<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'AppBundle\Controller\ResumeController' shared autowired service.

return $this->services['AppBundle\Controller\ResumeController'] = new \AppBundle\Controller\ResumeController();
